In [3]:
from yahoo_fin import stock_info as si
import yahoo_fin.options as ops
from datetime import datetime
from black_scholes import black_scholes_call

ticker = "aal"

# Options Data

In [4]:
# Get call options chain for particular ticker
call_options_df = ops.get_calls(ticker=ticker)
call_options_df.head(5)

/home/anurag/Documents/repos/optionsPricing/.venv/lib/python3.12/site-packages/yahoo_fin/options.py:42: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(requests.get(site, headers=headers).text)

,Contract Name,Last Trade Date (EDT),Strike,Last Price,Bid,Ask,Change,% Change,Volume,Open Interest,Implied Volatility
0,AAL240809C00002500,8/2/2024 3:42 PM,2.5,7.32,6.80,9.25,-0.51,-6.51%,6,21,"1,279.69%"
1,AAL240809C00007000,8/1/2024 6:44 PM,7.0,3.20,1.87,2.84,0.00,0.00%,1,3,228.13%
2,AAL240809C00007500,8/1/2024 1:39 PM,7.5,2.40,1.92,2.55,-0.73,-23.32%,1,21,153.13%
3,AAL240809C00008000,8/2/2024 6:41 PM,8.0,1.72,1.42,2.07,-1.18,-40.69%,12,2,126.56%
4,AAL240809C00008500,8/2/2024 7:55 PM,8.5,1.22,0.94,1.37,-1.23,-50.20%,11,2,61.72%

In [32]:
# Get put options chain for particular ticker
ops.get_puts(ticker=ticker)

/home/anurag/Documents/repos/optionsValuationAPI/.venv/lib/python3.12/site-packages/yahoo_fin/options.py:42: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(requests.get(site, headers=headers).text)

,Contract Name,Last Trade Date (EDT),Strike,Last Price,Bid,Ask,Change,% Change,Volume,Open Interest,Implied Volatility
0,AAPL240802P00100000,6/17/2024 1:30 PM,100.0,0.02,0.00,0.00,0.00,0.00%,-,1,50.00%
1,AAPL240802P00105000,7/24/2024 1:45 PM,105.0,0.01,0.00,0.01,0.00,0.00%,1,1,437.50%
2,AAPL240802P00110000,8/2/2024 1:30 PM,110.0,0.01,0.00,0.01,0.00,0.00%,2,1,412.50%
3,AAPL240802P00115000,8/1/2024 2:45 PM,115.0,0.01,0.00,0.01,0.00,0.00%,3,673,387.50%
4,AAPL240802P00120000,7/30/2024 3:03 PM,120.0,0.01,0.00,0.01,0.00,0.00%,9,17,362.50%
5,AAPL240802P00125000,7/17/2024 1:48 PM,125.0,0.01,0.00,0.01,0.00,0.00%,-,2,337.50%
6,AAPL240802P00130000,8/1/2024 6:15 PM,130.0,0.01,0.00,0.01,0.00,0.00%,2,105,318.75%
7,AAPL240802P00135000,7/25/2024 1:30 PM,135.0,0.02,0.00,0.01,0.00,0.00%,1,372,300.00%
8,AAPL240802P00140000,7/29/2024 1:30 PM,140.0,0.02,0.00,0.01,0.00,0.00%,5,60,275.00%
9,AAPL240802P00145000,7/31/2024 2:37 PM,145.0,0.01,0.00,0.01,0.00,0.00%,1,33,256.25%
10,AAPL240802P00150000,8/1/2024 7:57 PM,150.0,0.01,0.00,0.01,0.00,0.00%,9,122,237.50%
11,AAPL240802P00155000,7/29/2024 6:36 PM,155.0,0.01,0.00,0.01,0.00,0.00%,1,575,218.75%
12,AAPL240802P00160000,8/2/2024 6:18 PM,160.0,0.01,0.00,0.01,0.00,0.00%,10,710,200.00%
13,AAPL240802P00165000,8/1/2024 7:58 PM,165.0,0.01,0.00,0.01,0.00,0.00%,94,2381,181.25%
14,AAPL240802P00170000,8/2/2024 1:30 PM,170.0,0.01,0.00,0.01,0.00,0.00%,2,2449,168.75%
15,AAPL240802P00175000,8/2/2024 1:30 PM,175.0,0.01,0.00,0.01,0.00,0.00%,28,1998,150.00%
16,AAPL240802P00180000,8/2/2024 6:10 PM,180.0,0.01,0.00,0.01,-0.01,-50.00%,52,4096,134.38%
17,AAPL240802P00185000,8/2/2024 6:10 PM,185.0,0.01,0.00,0.01,-0.03,-75.00%,166,4872,118.75%
18,AAPL240802P00190000,8/2/2024 6:16 PM,190.0,0.01,0.00,0.01,-0.06,-85.71%,428,4753,103.13%
19,AAPL240802P00195000,8/2/2024 5:51 PM,195.0,0.01,0.00,0.01,-0.10,-90.91%,1036,5861,87.50%
20,AAPL240802P00197500,8/2/2024 5:55 PM,197.5,0.01,0.00,0.01,-0.14,-93.33%,329,4188,78.13%
21,AAPL240802P00200000,8/2/2024 6:48 PM,200.0,0.01,0.00,0.01,-0.24,-96.00%,2440,22104,71.88%
22,AAPL240802P00202500,8/2/2024 6:43 PM,202.5,0.01,0.00,0.01,-0.37,-97.37%,1757,4517,62.50%
23,AAPL240802P00205000,8/2/2024 6:34 PM,205.0,0.01,0.00,0.01,-0.56,-98.25%,8626,25173,56.25%
24,AAPL240802P00207500,8/2/2024 6:32 PM,207.5,0.01,0.00,0.01,-0.91,-98.91%,4762,17077,52.34%
25,AAPL240802P00210000,8/2/2024 6:47 PM,210.0,0.01,0.00,0.01,-1.39,-99.29%,21503,21867,43.75%
26,AAPL240802P00212500,8/2/2024 6:45 PM,212.5,0.01,0.00,0.02,-2.03,-99.51%,20883,6103,39.45%
27,AAPL240802P00215000,8/2/2024 6:48 PM,215.0,0.01,0.00,0.01,-3.09,-99.68%,73003,15571,28.13%
28,AAPL240802P00217500,8/2/2024 6:50 PM,217.5,0.02,0.01,0.02,-4.07,-99.51%,77715,5736,21.49%
29,AAPL240802P00220000,8/2/2024 6:52 PM,220.0,0.05,0.05,0.06,-5.45,-99.09%,111805,11327,15.14%
30,AAPL240802P00222500,8/2/2024 6:51 PM,222.5,0.34,0.32,0.36,-6.37,-95.07%,78769,10495,7.86%
31,AAPL240802P00225000,8/2/2024 6:52 PM,225.0,1.51,1.40,1.48,-6.94,-82.33%,39653,9051,0.00%
32,AAPL240802P00227500,8/2/2024 6:32 PM,227.5,4.00,3.80,3.95,-6.40,-61.54%,4877,2741,0.00%
33,AAPL240802P00230000,8/2/2024 6:49 PM,230.0,6.25,6.15,6.30,-6.84,-52.25%,2506,8564,0.00%
34,AAPL240802P00232500,8/2/2024 6:39 PM,232.5,8.70,8.15,8.80,-6.49,-42.73%,1833,1004,0.00%
35,AAPL240802P00235000,8/2/2024 5:53 PM,235.0,11.22,11.05,11.45,-6.28,-35.89%,165,2491,0.00%
36,AAPL240802P00237500,8/2/2024 5:14 PM,237.5,12.50,12.45,13.95,-7.50,-37.50%,68,158,0.00%
37,AAPL240802P00240000,8/2/2024 4:16 PM,240.0,16.85,16.10,16.45,-5.15,-23.41%,121,111,0.00%
38,AAPL240802P00242500,8/2/2024 3:36 PM,242.5,19.45,17.75,19.05,-2.35,-10.78%,8,8,0.00%
39,AAPL240802P00245000,8/2/2024 5:05 PM,245.0,19.90,21.00,21.50,-3.85,-16.21%,2,1,0.00%
40,AAPL240802P00247500,7/24/2024 3:04 PM,247.5,28.60,23.35,24.00,0.00,0.00%,5,0,0.00%
41,AAPL240802P00250000,8/2/2024 3:42 PM,250.0,28.00,25.60,26.65,-4.75,-14.50%,11,11,0.00%
42,AAPL240802P00252500,7/24/2024 3:04 PM,252.5,33.59,28.20,29.55,0.00,0.00%,5,0,0.00%
43,AAPL240802P00255000,7/30/2024 1:30 PM,255.0,36.00,30.20,32.30,0.00,0.00%,2,0,0.00%
44,AAPL240802P00257500,7/25/2024 7:36 PM,257.5,38.17,32.70,34.80,0.00,0.00%,5,0,0.00%
45,AAPL240802P00260000,7/29/2024 2:04 PM,260.0,41.44,34.95,37.30,0.00,0.00%,2,0,0.00%
46,AAPL240802P00265000,7/29/2024 4:48 PM,265.0,46.30,40.75,42.30,0.00,0.00%,2,0,0.00%
47,AAPL240802P00270000,8/1/2024 5:05 PM,270.0,51.22,45.60,47.30,0.00,0.00%,3,0,0.00%

## Real-Time Stock Price

In [33]:
# Collect realtime stock price for particular ticker
stock_price_live = si.get_live_price(ticker=ticker).item()
stock_price_live

/home/anurag/Documents/repos/optionsValuationAPI/.venv/lib/python3.12/site-packages/yahoo_fin/stock_info.py:580: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  return df.close[-1]

222.50999450683594

# Data Manipulation into Output

## Options Data Formatting

In [34]:
def decimalise(x):
    """
    this function remove % string"""
    x = x.replace('%', '')
    return float(x) / 100

In [35]:
# Setup the Options Data into the results
result_df = call_options_df.loc[:, ['Contract Name', 'Strike', 'Last Price', 'Implied Volatility']]
result_df.insert(0, column='ticker', value=ticker)
result_df.rename(columns={'Contract Name': 'contract_name', 
                          'Last Price': 'premium',
                          'Strike': 'strike',
                          'Implied Volatility': 'volatility'}, inplace=True)

result_df['volatility'] = result_df['volatility'].apply(decimalise)

result_df.head(5)

  ticker        contract_name  strike  premium  volatility
0   AAPL  AAPL240802C00100000   100.0   120.28      8.9063
1   AAPL  AAPL240802C00115000   115.0   100.06      5.1406
2   AAPL  AAPL240802C00125000   125.0    93.58      6.6895
3   AAPL  AAPL240802C00135000   135.0    88.35      5.9688
4   AAPL  AAPL240802C00140000   140.0    77.84      5.5527

## Stock Data Formatting

In [36]:
result_df['stock_price'] = stock_price_live

result_df.head(5)

  ticker        contract_name  strike  premium  volatility  stock_price
0   AAPL  AAPL240802C00100000   100.0   120.28      8.9063   222.509995
1   AAPL  AAPL240802C00115000   115.0   100.06      5.1406   222.509995
2   AAPL  AAPL240802C00125000   125.0    93.58      6.6895   222.509995
3   AAPL  AAPL240802C00135000   135.0    88.35      5.9688   222.509995
4   AAPL  AAPL240802C00140000   140.0    77.84      5.5527   222.509995

## Other Variable Formatting

In [37]:
interest_rate = 0.06 #TODO: Use API for this
result_df['interest_rate'] = interest_rate

result_df.head(5)

,ticker,contract_name,strike,premium,volatility,stock_price,interest_rate
0,AAPL,AAPL240802C00100000,100.0,120.28,8.9063,222.509995,0.06
1,AAPL,AAPL240802C00115000,115.0,100.06,5.1406,222.509995,0.06
2,AAPL,AAPL240802C00125000,125.0,93.58,6.6895,222.509995,0.06
3,AAPL,AAPL240802C00135000,135.0,88.35,5.9688,222.509995,0.06
4,AAPL,AAPL240802C00140000,140.0,77.84,5.5527,222.509995,0.06

In [38]:
# Time to Expiry Calculation
def expiry_from_contract(contract_name, ticker):
    """
    retrive expiry date from contract name"""
    n = len(ticker)
    expiry_date_string = contract_name[n:n+6]
    expiry_date = datetime.strptime(expiry_date_string, "%y%m%d")
    return expiry_date.date()

def time_to_expiry(contract_name, ticker):
    """
    Calculate number of yrs for contract"""
    today = datetime.today().date()
    expiry = expiry_from_contract(contract_name=contract_name, ticker=ticker)
    delta = expiry - today
    days = delta.days + 1
    return float(days / 365)

#time_to_expiry('AAPL24080500030000')

In [39]:
#result_df['time_to_expiry'] = result_df['contract_name'].apply(time_to_expiry)
result_df['time_to_expiry'] = result_df.apply(lambda x: time_to_expiry(x['contract_name'], ticker), axis=1)

result_df.head(5)

,ticker,contract_name,strike,premium,volatility,stock_price,interest_rate,time_to_expiry
0,AAPL,AAPL240802C00100000,100.0,120.28,8.9063,222.509995,0.06,0.00274
1,AAPL,AAPL240802C00115000,115.0,100.06,5.1406,222.509995,0.06,0.00274
2,AAPL,AAPL240802C00125000,125.0,93.58,6.6895,222.509995,0.06,0.00274
3,AAPL,AAPL240802C00135000,135.0,88.35,5.9688,222.509995,0.06,0.00274
4,AAPL,AAPL240802C00140000,140.0,77.84,5.5527,222.509995,0.06,0.00274

## Model Calculation

In [40]:
def call_option_value(x):
    """
    Apply Model"""
    ret_val = -1
    if x['volatility'] > 0:
        ret_val = black_scholes_call(
        S=x['stock_price'],
        K=x['strike'],
        T=x['time_to_expiry'],
        r=x['interest_rate'],
        sig=x['volatility']
        )
    return round(float(ret_val),2)

In [41]:
result_df.loc[:,'fair_price'] = result_df.apply(lambda x: call_option_value(x), axis=1)

result_df.head(5)

,ticker,contract_name,strike,premium,volatility,stock_price,interest_rate,time_to_expiry,fair_price
0,AAPL,AAPL240802C00100000,100.0,120.28,8.9063,222.509995,0.06,0.00274,123.72
1,AAPL,AAPL240802C00115000,115.0,100.06,5.1406,222.509995,0.06,0.00274,107.63
2,AAPL,AAPL240802C00125000,125.0,93.58,6.6895,222.509995,0.06,0.00274,98.73
3,AAPL,AAPL240802C00135000,135.0,88.35,5.9688,222.509995,0.06,0.00274,88.78
4,AAPL,AAPL240802C00140000,140.0,77.84,5.5527,222.509995,0.06,0.00274,83.73

In [42]:
def label_valuation(ask_price,fair_price):
    """
    Label valuations"""
    if fair_price < 0:
        return 'N/A'
    elif ask_price > fair_price:
        return 'Overvalued'
    elif ask_price < fair_price:
        return 'Undervalued'
    else:
        return 'Fair Value'

In [43]:
result_df['valuation'] = result_df.apply(lambda x: label_valuation(x['premium'], x['fair_price']), axis=1)
result_df.head(5)

,ticker,contract_name,strike,premium,volatility,stock_price,interest_rate,time_to_expiry,fair_price,valuation
0,AAPL,AAPL240802C00100000,100.0,120.28,8.9063,222.509995,0.06,0.00274,123.72,Undervalued
1,AAPL,AAPL240802C00115000,115.0,100.06,5.1406,222.509995,0.06,0.00274,107.63,Undervalued
2,AAPL,AAPL240802C00125000,125.0,93.58,6.6895,222.509995,0.06,0.00274,98.73,Undervalued
3,AAPL,AAPL240802C00135000,135.0,88.35,5.9688,222.509995,0.06,0.00274,88.78,Undervalued
4,AAPL,AAPL240802C00140000,140.0,77.84,5.5527,222.509995,0.06,0.00274,83.73,Undervalued